### ISSUE TITLE
The packet "MariaDB-server" is missing

### ISSUE THREAD

**Issue by sizeur** [centreon/centreon-poller-display#2]
Hello,

When we install centreon-poller-display (1.5.2-2) on an existing poller, after installing the 2 packages centreon-base-config-centreon-engine centreon-poller-display, there is an error message when we install the web interface:
![error1](https://cloud.githubusercontent.com/assets/13485588/18835377/1d586194-83fb-11e6-898a-d15d90ee4a6a.png)

We need to install manually the packet "MariaDB-server" to solve the problem.

**Comment by lpinsivy** [comment]
As centreon-web central server, the DBMS can be deported.

So I can't include this require in Centreon Poller Display package.

Regards,
