### ISSUE TITLE
Empty pages with the 2.7.7 update

### ISSUE THREAD

**Issue by sizeur** [centreon/centreon-poller-display#4]
Hello,

When we upgrade the centreon-poller-display to the version 2.7.7 (from CES 3.3 fresh isntall for example) the pages monitoring/configuration are blank, there is no host or services displayed. But all the information arrive normally to the  web interface of the central server.

**Comment by lpinsivy** [comment]
Did you try to restart centengine after update ?

**Comment by sizeur** [comment]
Hello,

It was 5 months ago i don't remember but thank you anyway ...
